chatapp/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views as user_views

urlpatterns = [
    path('', include('chatroom.urls')), 
    path('admin/', admin.site.urls),

    path('register/', user_views.registerUser, name="register"),
    path('login/', user_views.loginUser, name="login"),
    path('logout/', user_views.logoutUser, name="logout"),
]

chatroom/urls.py
from django.urls import path
from . import views
  

app_name = 'chatroom'
urlpatterns = [
    path('', views.index, name="room-home"),
    path('room/<str:id>/', views.roomMessage, name="room-message"),
    path('create-room/<str:id>/', views.createRoom, name="create-room"),
   
]

chatroom/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    date_created = models.DateTimeField(default=timezone.now) 
    created_by = models.ForeignKey(User, default="", null="True", blank="True", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Messages(models.Model):
    value = models.CharField(max_length=200)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    message_created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.value    

users/models.py
from django.db import models

# Create your models here.

chatroom/forms.py
from django import forms
from django.forms import ModelForm, fields
from . models import *

class MessageForm(forms.ModelForm):

    class Meta:
        model = Messages
        widgets = {'room': forms.HiddenInput()}
        fields = '__all__'
        exclude = ['message_created_on']

class RoomForm(forms.ModelForm):

    class Meta:
        model = Room
        widgets = {'created_by': forms.HiddenInput()}
        fields = '__all__'
        exclude = ['date_created']        

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

chatroom/views.py
from django.shortcuts import redirect, render
from . models import Messages, Room
from django.urls import reverse
from . forms import *

from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    room_details = Room.objects.order_by('-date_created')

    context={'room_details':room_details}
    return render(request, 'chatroom/index.html', context)

@login_required(login_url='login')
def roomMessage(request, id):
    room = Room.objects.get(id=id)

    message = Messages.objects.filter(room=id)
    form = MessageForm(initial={'room':room})
    
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('chatroom:room-message', args=id))
            
    context={'message':message, 'form':form}
    return render(request, 'chatroom/room_message.html', context) 

@login_required(login_url='login')
def createRoom(request, id):
    created_by = User.objects.get(id=id)
    form = RoomForm(initial={'created_by':created_by})

    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('chatroom:room-home')

    context={'form':form}
    return render(request, 'chatroom/create_room.html', context)      
   

users/views.py
from django.shortcuts import redirect, render
from . forms import *

from django.contrib.auth import authenticate, login, logout

# Create your views here.
def registerUser(request):
    forms = UserRegisterForm()

    if request.method == 'POST':
        forms = UserRegisterForm(request.POST)
        if forms.is_valid():
            forms.save()
            return redirect('login')

    context = {'forms':forms}
    return render(request, 'users/register.html', context)

def loginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('chatroom:room-home')

    context = {}
    return render(request, 'users/login.html', context)   

def logoutUser(request):
    logout(request)
    return redirect('chatroom:room-home')     

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-light bg-light" style="position:fixed; width:100%; top:0; z-index:1;">
            <div class="container-fluid">
              <span class="navbar-brand mb-0 h1">Chat House</span>
              
              {% if user.is_authenticated %}
              <a href="{% url 'logout' %}">Logout</a>
              <h4>Hello {{user.username}}!</h4>
              <form method="" action="{% url 'chatroom:room-home' %}" class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search Room" aria-label="Search" name="room-name">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
              {% else %}
              <a href="{% url 'login' %}">Login</a>
              {% endif %}

            </div>
          </nav>
    </header>
    <section>
    <div class="container" style="padding-top: 75px;">
        <div class="row">
            <div class="col-md-8">
              {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</section>

</body>
</html>

templates/chatroom/create_room.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}
<div style="margin-top: 50px;">
<a href="{% url 'chatroom:room-home' %}">Back Home</a>
<form method="POST" action="">
    {% csrf_token %}
{{form|crispy}}
<input class="btn btn-info" type="submit" name="send_message">
</form>
</div>

{% endblock %}

templates/chatroom/index.html
{% extends 'base.html' %}
{% block content %}
  
  {% for details in room_details %}
<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{details.name}}</h5>
      <p class="card-text">{{details.description}}</p>
      <small class="text-muted">Created by : {{ details.created_by }}</small><br>
      <small class="text-muted">Created on : {{ details.date_created|date:"F d, Y" }}</small><br><hr>
      <a href="{% url 'chatroom:room-message' details.id %}" class="btn btn-primary">Enter Room</a>
    </div>
</div><br>
  {% endfor %}
<footer class="d-flex justify-content-center">
      <a class="btn btn-outline-success" href="{% url 'chatroom:create-room' request.user.id %}">Create Room</a>
</footer>  
{% endblock %}

templates/chatroom/room_message.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}

<div  style="margin-top: 50px;">
<form method="POST" action="">
  {% csrf_token %}
 
   {{form|crispy}}
  
   <input class="btn btn-info" type="submit" name="send_message">

</form>
<a href="{% url 'chatroom:room-home' %}">Back Home</a>


{% for messages in message %}
 
    <div class="card">
      <div class="card-body">
        {{messages.value}}
        <small class="text-muted">{{messages.message_created_on}}</small>
      </div>
    </div>
 
{% endfor %}
</div>

{% endblock %}

templates/users/login.html
<h1>Login</h1>
<div class="content-section">
    <form method="POST" action="">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" name="username" placeholder="Username..." class="form-control">
        </div>
        <div class="input-group mb-2">
            <div class="input-group-append">
                <span class="input-group-text"><i class="fas fa-key"></i></span>
            </div>
            <input type="password" name="password" placeholder="Password..." class="form-control" >
        </div>

        <div class="d-flex justify-content-center mt-3 login_container">
            <input class="btn btn-danger" type="submit" value="Login">
        </div>
        <div>
            <small class="text-muted">
                Don't you have an Account? <a class="ml-2" href="{% url 'register' %}">Register</a>
            </small>
        </div>
    </form>

</div>

templates/users/register.html
{% load crispy_forms_filters %}
<h1>Register User</h1>

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{forms|crispy}}
        <input class="btn btn-info" type="submit" name="register-user">
    </form>
    <small>Already have an Account?<a href="{% url 'login' %}">Login</a></small>
</div>